name: Build_EVE_App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build EXE
        run: |
          npm install -g nwjs-builder-phoenix
          npx nwjs-builder-phoenix --targets=win-x64 --out dist .
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: EVE_Robot_Exe
          path: dist/
